# Generated by Django 4.1.1 on 2022-12-04 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('creador', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo_name', models.CharField(max_length=50, unique=True)),
                ('descripcion_flujo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('plazo_flujo', models.CharField(max_length=50)),
                ('creador_flujo', models.PositiveIntegerField()),
                ('ejecutar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=50, unique=True)),
                ('descripcion_tarea', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('plazo_tarea', models.CharField(max_length=255)),
                ('progreso_tarea', models.CharField(max_length=255)),
                ('creador_tarea', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TareaRelacionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea_main', models.PositiveIntegerField(null=True)),
                ('id_tarea_relational', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignador', models.PositiveIntegerField()),
                ('estado_tarea', models.CharField(choices=[('0', 'Sin asignar'), ('1', 'Por empezar'), ('2', 'En progreso'), ('3', 'Finalizada'), ('4', 'Aceptada'), ('5', 'Rechazada')], default=None, max_length=12)),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTSubTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_padre', models.PositiveIntegerField()),
                ('asignador', models.PositiveIntegerField()),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userTarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertarea')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignador', models.IntegerField()),
                ('flujo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.flujo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_name', models.CharField(max_length=255, null=True, unique=True)),
                ('dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='TareaSubordinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_subTarea', models.CharField(max_length=30, unique=True)),
                ('descripcion_subTarea', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reportador_rechazador', models.PositiveIntegerField()),
                ('justificacion', models.CharField(max_length=255)),
                ('is_reported', models.BooleanField(default=False)),
                ('asignador_tarea', models.PositiveIntegerField()),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reg_f', models.CharField(max_length=255, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('userFlujo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userflujo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reg', models.CharField(max_length=255, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True, null=True)),
                ('userTarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertarea')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_notificador', models.PositiveIntegerField()),
                ('id_notificado', models.PositiveIntegerField()),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
