# Generated by Django 4.1.1 on 2022-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado_tarea',
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador_tarea',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertarea',
            name='asignador',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertarea',
            name='estado_tarea',
            field=models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('En progreso', 'En progreso'), ('Finalizada', 'Finalizada')], default='Sin asignar', max_length=12),
        ),
    ]
