# Generated by Django 4.1.1 on 2022-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujo',
            name='ejecutar',
            field=models.CharField(choices=[('1', 'Seleccionar'), ('2', 'Activar'), ('3', 'Desactivar')], max_length=10),
        ),
    ]
