# Generated by Django 4.1.1 on 2022-12-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flujo',
            name='atraso',
        ),
    ]
