# Generated by Django 4.1.1 on 2022-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertarea',
            name='estado_tarea',
            field=models.IntegerField(choices=[('Sin asignar', '1'), ('En progreso', '2'), ('Finalizada', '3')]),
        ),
    ]
