# Generated by Django 4.1.1 on 2022-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertarea',
            name='estado_tarea',
            field=models.CharField(choices=[('0', 'Sin asignar'), ('1', 'Por empezar'), ('2', 'En progreso'), ('3', 'Finalizada'), ('4', 'Aceptada'), ('5', 'Rechazada')], default=None, max_length=12),
        ),
    ]
