# Generated by Django 4.1.1 on 2022-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tarea_estado_tarea_tarea_creador_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='creador_tarea',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertarea',
            name='asignador',
            field=models.IntegerField(null=True),
        ),
    ]
