# Generated by Django 4.1.1 on 2022-12-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_flujo_atraso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id_tarea',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea'),
        ),
    ]
