# Generated by Django 4.1.1 on 2022-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_flujo_user_alter_unidad_dir_alter_user_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='fecha_hoy',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
