# Generated by Django 4.1.1 on 2022-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tarea_creador_tarea_alter_usertarea_asignador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='creador_tarea',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertarea',
            name='asignador',
            field=models.IntegerField(default=0),
        ),
    ]
