# Generated by Django 4.1.1 on 2022-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_direccion_fecha_hoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='fecha_hoy',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
