# Generated by Django 4.1.1 on 2022-12-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tarearelacionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.CharField(max_length=255)),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.DeleteModel(
            name='Alertas',
        ),
    ]
