# Generated by Django 4.1.1 on 2022-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_direccion_fecha_hoy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='fecha_hoy',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='registroejecucion',
            name='fecha_reg',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareasubordinada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareasubordinada',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tareasubordinada',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
