# Generated by Django 4.1.1 on 2022-10-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rol_delete_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_flujo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_name', models.CharField(max_length=30, unique=True)),
                ('descripcion_estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_flujo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion', models.BooleanField(null=True)),
                ('justificacion', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=30, unique=True)),
                ('descripcion_tarea', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_limite', models.DateField(null=True)),
                ('progreso_tarea', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TareaSubordinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea_sub', models.CharField(max_length=30, unique=True)),
                ('descripcion_tarea_sub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
