# Generated by Django 4.1.1 on 2022-10-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detalleflujo_estadotarea_flujo_registroejecucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dir_user',
        ),
    ]
