# Generated by Django 4.1.1 on 2022-11-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_flujo_plazo_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroejecucion',
            name='userFlujo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userflujo'),
        ),
    ]
