# Generated by Django 4.1.1 on 2022-10-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_dir_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_administrador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_disenador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_funcionario',
        ),
        migrations.AddField(
            model_name='user',
            name='rol_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
    ]
