# Generated by Django 4.1.1 on 2022-10-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_is_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rol_name',
            new_name='rol_id',
        ),
    ]
