# Generated by Django 4.1.1 on 2022-10-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_rol_name_user_rol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dir_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.direccion'),
        ),
    ]
