# Generated by Django 4.1.1 on 2022-10-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_dir_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='unidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidad'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='unidad_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
