# Generated by Django 4.1.1 on 2022-10-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cargo_detalleflujo_flujo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='unidad_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='dir_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rol_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
            preserve_default=False,
        ),
    ]
