# Generated by Django 4.1.1 on 2022-10-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_rol_unidad_id_alter_user_cargo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='unidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dir_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
    ]
