# Generated by Django 4.1.1 on 2022-10-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_rol_unidad_id_alter_user_cargo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='unidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='core.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together={('rol_name',)},
        ),
    ]
