# Generated by Django 4.1.1 on 2022-10-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alerta_usertarea_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerta',
            new_name='Alertas',
        ),
    ]
