# Generated by Django 4.1.1 on 2022-10-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rol_unidad_id_alter_rol_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rol',
            name='unidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.unidad'),
        ),
    ]
