# Generated by Django 4.1.1 on 2022-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_tarea_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='hora_limite',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
    ]
