# Generated by Django 4.1.1 on 2022-10-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_user_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creador',
            field=models.IntegerField(default=0),
        ),
    ]
