# Generated by Django 4.1.1 on 2022-10-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_limite',
        ),
    ]
