# Generated by Django 4.1.1 on 2022-10-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_tarea_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
