# Generated by Django 4.1.1 on 2022-10-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
    ]
