# Generated by Django 4.1.1 on 2022-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado_tarea',
            field=models.CharField(choices=[('0', '--------'), ('1', 'En progreso'), ('2', 'Finalizado')], default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
    ]
