# Generated by Django 4.1.1 on 2022-10-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_tarea_estado_tarea_estado_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado_tarea',
            field=models.CharField(choices=[('Sin asignar', 'Sin asignar'), ('En progreso', 'En progreso'), ('Finalizada', 'Finalizada')], default='Sin asignar', max_length=12),
        ),
    ]
