# Generated by Django 4.1.1 on 2022-10-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_tarea_progreso_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='progreso_tarea',
            new_name='plazo_tarea',
        ),
    ]
