# Generated by Django 4.1.1 on 2022-10-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_progreso_tarea_tarea_plazo_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='progreso_tarea',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
